/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Symend.Client.Customer.Client;
using Symend.Client.Customer.Model;

namespace Symend.Client.Customer.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDataTargetDefinitionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new Data Target Definition
        /// </summary>
        /// <remarks>
        /// Create a new attribute for use in mapping Account data.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataTargetDefinitionModelResultModel</returns>
        DataTargetDefinitionModelResultModel CreateDataTargetDefinition(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0);

        /// <summary>
        /// Create a new Data Target Definition
        /// </summary>
        /// <remarks>
        /// Create a new attribute for use in mapping Account data.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataTargetDefinitionModelResultModel</returns>
        ApiResponse<DataTargetDefinitionModelResultModel> CreateDataTargetDefinitionWithHttpInfo(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0);
        /// <summary>
        /// Get Data Target Definition by Id
        /// </summary>
        /// <remarks>
        /// Returns a specific data attribute by its ID.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataTargetDefinitionModelResultModel</returns>
        DataTargetDefinitionModelResultModel GetDataTargetDefinition(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0);

        /// <summary>
        /// Get Data Target Definition by Id
        /// </summary>
        /// <remarks>
        /// Returns a specific data attribute by its ID.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataTargetDefinitionModelResultModel</returns>
        ApiResponse<DataTargetDefinitionModelResultModel> GetDataTargetDefinitionWithHttpInfo(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0);
        /// <summary>
        /// List of Data Target Definitions
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a list format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataTargetDefinitionSearchResultGuidPagedModel</returns>
        DataTargetDefinitionSearchResultGuidPagedModel GetDataTargetDefinitions(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0);

        /// <summary>
        /// List of Data Target Definitions
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a list format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataTargetDefinitionSearchResultGuidPagedModel</returns>
        ApiResponse<DataTargetDefinitionSearchResultGuidPagedModel> GetDataTargetDefinitionsWithHttpInfo(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0);
        /// <summary>
        /// List of Data Target Definitions (dictionary)
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a dictionary format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel</returns>
        GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel GetDataTargetDefinitionsDictionary(Guid xSymOrganizationId, int operationIndex = 0);

        /// <summary>
        /// List of Data Target Definitions (dictionary)
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a dictionary format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel</returns>
        ApiResponse<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel> GetDataTargetDefinitionsDictionaryWithHttpInfo(Guid xSymOrganizationId, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDataTargetDefinitionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new Data Target Definition
        /// </summary>
        /// <remarks>
        /// Create a new attribute for use in mapping Account data.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataTargetDefinitionModelResultModel</returns>
        System.Threading.Tasks.Task<DataTargetDefinitionModelResultModel> CreateDataTargetDefinitionAsync(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a new Data Target Definition
        /// </summary>
        /// <remarks>
        /// Create a new attribute for use in mapping Account data.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataTargetDefinitionModelResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataTargetDefinitionModelResultModel>> CreateDataTargetDefinitionWithHttpInfoAsync(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Data Target Definition by Id
        /// </summary>
        /// <remarks>
        /// Returns a specific data attribute by its ID.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataTargetDefinitionModelResultModel</returns>
        System.Threading.Tasks.Task<DataTargetDefinitionModelResultModel> GetDataTargetDefinitionAsync(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Data Target Definition by Id
        /// </summary>
        /// <remarks>
        /// Returns a specific data attribute by its ID.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataTargetDefinitionModelResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataTargetDefinitionModelResultModel>> GetDataTargetDefinitionWithHttpInfoAsync(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List of Data Target Definitions
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a list format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataTargetDefinitionSearchResultGuidPagedModel</returns>
        System.Threading.Tasks.Task<DataTargetDefinitionSearchResultGuidPagedModel> GetDataTargetDefinitionsAsync(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List of Data Target Definitions
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a list format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataTargetDefinitionSearchResultGuidPagedModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataTargetDefinitionSearchResultGuidPagedModel>> GetDataTargetDefinitionsWithHttpInfoAsync(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List of Data Target Definitions (dictionary)
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a dictionary format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel</returns>
        System.Threading.Tasks.Task<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel> GetDataTargetDefinitionsDictionaryAsync(Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List of Data Target Definitions (dictionary)
        /// </summary>
        /// <remarks>
        /// Returns a list of all possible attributes for an Account in a dictionary format.
        /// </remarks>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel>> GetDataTargetDefinitionsDictionaryWithHttpInfoAsync(Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDataTargetDefinitionsApi : IDataTargetDefinitionsApiSync, IDataTargetDefinitionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DataTargetDefinitionsApi : IDataTargetDefinitionsApi
    {
        private Symend.Client.Customer.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTargetDefinitionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DataTargetDefinitionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTargetDefinitionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DataTargetDefinitionsApi(string basePath)
        {
            this.Configuration = Symend.Client.Customer.Client.Configuration.MergeConfigurations(
                Symend.Client.Customer.Client.GlobalConfiguration.Instance,
                new Symend.Client.Customer.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Symend.Client.Customer.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Symend.Client.Customer.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Symend.Client.Customer.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTargetDefinitionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DataTargetDefinitionsApi(Symend.Client.Customer.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Symend.Client.Customer.Client.Configuration.MergeConfigurations(
                Symend.Client.Customer.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Symend.Client.Customer.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Symend.Client.Customer.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Symend.Client.Customer.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTargetDefinitionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DataTargetDefinitionsApi(Symend.Client.Customer.Client.ISynchronousClient client, Symend.Client.Customer.Client.IAsynchronousClient asyncClient, Symend.Client.Customer.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Symend.Client.Customer.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Symend.Client.Customer.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Symend.Client.Customer.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Symend.Client.Customer.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Symend.Client.Customer.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new Data Target Definition Create a new attribute for use in mapping Account data.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataTargetDefinitionModelResultModel</returns>
        public DataTargetDefinitionModelResultModel CreateDataTargetDefinition(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0)
        {
            Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel> localVarResponse = CreateDataTargetDefinitionWithHttpInfo(xSymOrganizationId, dataTargetDefinitionForm);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new Data Target Definition Create a new attribute for use in mapping Account data.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataTargetDefinitionModelResultModel</returns>
        public Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel> CreateDataTargetDefinitionWithHttpInfo(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0)
        {
            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter
            localVarRequestOptions.Data = dataTargetDefinitionForm;

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.CreateDataTargetDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DataTargetDefinitionModelResultModel>("/v1/data-target-definitions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDataTargetDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new Data Target Definition Create a new attribute for use in mapping Account data.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataTargetDefinitionModelResultModel</returns>
        public async System.Threading.Tasks.Task<DataTargetDefinitionModelResultModel> CreateDataTargetDefinitionAsync(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel> localVarResponse = await CreateDataTargetDefinitionWithHttpInfoAsync(xSymOrganizationId, dataTargetDefinitionForm, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new Data Target Definition Create a new attribute for use in mapping Account data.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionForm"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataTargetDefinitionModelResultModel)</returns>
        public async System.Threading.Tasks.Task<Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel>> CreateDataTargetDefinitionWithHttpInfoAsync(Guid xSymOrganizationId, DataTargetDefinitionForm dataTargetDefinitionForm = default(DataTargetDefinitionForm), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter
            localVarRequestOptions.Data = dataTargetDefinitionForm;

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.CreateDataTargetDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<DataTargetDefinitionModelResultModel>("/v1/data-target-definitions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDataTargetDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Data Target Definition by Id Returns a specific data attribute by its ID.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataTargetDefinitionModelResultModel</returns>
        public DataTargetDefinitionModelResultModel GetDataTargetDefinition(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0)
        {
            Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel> localVarResponse = GetDataTargetDefinitionWithHttpInfo(dataTargetDefinitionId, xSymOrganizationId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Data Target Definition by Id Returns a specific data attribute by its ID.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataTargetDefinitionModelResultModel</returns>
        public Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel> GetDataTargetDefinitionWithHttpInfo(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0)
        {
            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("dataTargetDefinitionId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(dataTargetDefinitionId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.GetDataTargetDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DataTargetDefinitionModelResultModel>("/v1/data-target-definitions/{dataTargetDefinitionId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDataTargetDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Data Target Definition by Id Returns a specific data attribute by its ID.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataTargetDefinitionModelResultModel</returns>
        public async System.Threading.Tasks.Task<DataTargetDefinitionModelResultModel> GetDataTargetDefinitionAsync(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel> localVarResponse = await GetDataTargetDefinitionWithHttpInfoAsync(dataTargetDefinitionId, xSymOrganizationId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Data Target Definition by Id Returns a specific data attribute by its ID.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dataTargetDefinitionId">Data Target Definition Id</param>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataTargetDefinitionModelResultModel)</returns>
        public async System.Threading.Tasks.Task<Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionModelResultModel>> GetDataTargetDefinitionWithHttpInfoAsync(Guid dataTargetDefinitionId, Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("dataTargetDefinitionId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(dataTargetDefinitionId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.GetDataTargetDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DataTargetDefinitionModelResultModel>("/v1/data-target-definitions/{dataTargetDefinitionId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDataTargetDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List of Data Target Definitions Returns a list of all possible attributes for an Account in a list format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataTargetDefinitionSearchResultGuidPagedModel</returns>
        public DataTargetDefinitionSearchResultGuidPagedModel GetDataTargetDefinitions(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0)
        {
            Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionSearchResultGuidPagedModel> localVarResponse = GetDataTargetDefinitionsWithHttpInfo(xSymOrganizationId, dataTargetDefinitionSearchCriteria, paging);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List of Data Target Definitions Returns a list of all possible attributes for an Account in a list format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataTargetDefinitionSearchResultGuidPagedModel</returns>
        public Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionSearchResultGuidPagedModel> GetDataTargetDefinitionsWithHttpInfo(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0)
        {
            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (dataTargetDefinitionSearchCriteria != null)
            {
                localVarRequestOptions.QueryParameters.Add(Symend.Client.Customer.Client.ClientUtils.ParameterToMultiMap("", "DataTargetDefinitionSearchCriteria", dataTargetDefinitionSearchCriteria));
            }
            if (paging != null)
            {
                localVarRequestOptions.QueryParameters.Add(Symend.Client.Customer.Client.ClientUtils.ParameterToMultiMap("", "paging", paging));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.GetDataTargetDefinitions";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DataTargetDefinitionSearchResultGuidPagedModel>("/v1/data-target-definitions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDataTargetDefinitions", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List of Data Target Definitions Returns a list of all possible attributes for an Account in a list format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataTargetDefinitionSearchResultGuidPagedModel</returns>
        public async System.Threading.Tasks.Task<DataTargetDefinitionSearchResultGuidPagedModel> GetDataTargetDefinitionsAsync(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionSearchResultGuidPagedModel> localVarResponse = await GetDataTargetDefinitionsWithHttpInfoAsync(xSymOrganizationId, dataTargetDefinitionSearchCriteria, paging, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List of Data Target Definitions Returns a list of all possible attributes for an Account in a list format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="dataTargetDefinitionSearchCriteria">Data Target Definition Search Criteria (optional)</param>
        /// <param name="paging">Paging Criteria (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataTargetDefinitionSearchResultGuidPagedModel)</returns>
        public async System.Threading.Tasks.Task<Symend.Client.Customer.Client.ApiResponse<DataTargetDefinitionSearchResultGuidPagedModel>> GetDataTargetDefinitionsWithHttpInfoAsync(Guid xSymOrganizationId, GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter dataTargetDefinitionSearchCriteria = default(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter), GuidPagedMetadata paging = default(GuidPagedMetadata), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (dataTargetDefinitionSearchCriteria != null)
            {
                localVarRequestOptions.QueryParameters.Add(Symend.Client.Customer.Client.ClientUtils.ParameterToMultiMap("", "DataTargetDefinitionSearchCriteria", dataTargetDefinitionSearchCriteria));
            }
            if (paging != null)
            {
                localVarRequestOptions.QueryParameters.Add(Symend.Client.Customer.Client.ClientUtils.ParameterToMultiMap("", "paging", paging));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.GetDataTargetDefinitions";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DataTargetDefinitionSearchResultGuidPagedModel>("/v1/data-target-definitions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDataTargetDefinitions", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List of Data Target Definitions (dictionary) Returns a list of all possible attributes for an Account in a dictionary format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel</returns>
        public GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel GetDataTargetDefinitionsDictionary(Guid xSymOrganizationId, int operationIndex = 0)
        {
            Symend.Client.Customer.Client.ApiResponse<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel> localVarResponse = GetDataTargetDefinitionsDictionaryWithHttpInfo(xSymOrganizationId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List of Data Target Definitions (dictionary) Returns a list of all possible attributes for an Account in a dictionary format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel</returns>
        public Symend.Client.Customer.Client.ApiResponse<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel> GetDataTargetDefinitionsDictionaryWithHttpInfo(Guid xSymOrganizationId, int operationIndex = 0)
        {
            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.GetDataTargetDefinitionsDictionary";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel>("/v1/data-target-definitions/dictionary", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDataTargetDefinitionsDictionary", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List of Data Target Definitions (dictionary) Returns a list of all possible attributes for an Account in a dictionary format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel</returns>
        public async System.Threading.Tasks.Task<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel> GetDataTargetDefinitionsDictionaryAsync(Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Symend.Client.Customer.Client.ApiResponse<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel> localVarResponse = await GetDataTargetDefinitionsDictionaryWithHttpInfoAsync(xSymOrganizationId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List of Data Target Definitions (dictionary) Returns a list of all possible attributes for an Account in a dictionary format.
        /// </summary>
        /// <exception cref="Symend.Client.Customer.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSymOrganizationId">Organization UUID of the client making the request</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel)</returns>
        public async System.Threading.Tasks.Task<Symend.Client.Customer.Client.ApiResponse<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel>> GetDataTargetDefinitionsDictionaryWithHttpInfoAsync(Guid xSymOrganizationId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Symend.Client.Customer.Client.RequestOptions localVarRequestOptions = new Symend.Client.Customer.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Symend.Client.Customer.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Symend.Client.Customer.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Sym-OrganizationId", Symend.Client.Customer.Client.ClientUtils.ParameterToString(xSymOrganizationId)); // header parameter

            localVarRequestOptions.Operation = "DataTargetDefinitionsApi.GetDataTargetDefinitionsDictionary";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (JSON_Web_Token) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GuidDataTargetDefinitionDictionaryModelIDictionaryResultModel>("/v1/data-target-definitions/dictionary", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDataTargetDefinitionsDictionary", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
