/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Symend.Client.Customer.Client;
using Symend.Client.Customer.Api;
// uncomment below to import models
//using Symend.Client.Customer.Model;

namespace Symend.Client.Customer.Test.Api
{
    /// <summary>
    ///  Class for testing AccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AccountsApiTests : IDisposable
    {
        private AccountsApi instance;

        public AccountsApiTests()
        {
            instance = new AccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AccountsApi
            //Assert.IsType<AccountsApi>(instance);
        }

        /// <summary>
        /// Test CreateUpdateAccount
        /// </summary>
        [Fact]
        public void CreateUpdateAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid xSymOrganizationId = null;
            //AccountForm accountForm = null;
            //var response = instance.CreateUpdateAccount(xSymOrganizationId, accountForm);
            //Assert.IsType<AccountResponseResultModel>(response);
        }

        /// <summary>
        /// Test GetAccount
        /// </summary>
        [Fact]
        public void GetAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid xSymOrganizationId = null;
            //var response = instance.GetAccount(id, xSymOrganizationId);
            //Assert.IsType<AccountExtendedModelResultModel>(response);
        }

        /// <summary>
        /// Test ListAccounts
        /// </summary>
        [Fact]
        public void ListAccountsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid xSymOrganizationId = null;
            //string accountKey = null;
            //string email = null;
            //string phone = null;
            //int? limit = null;
            //string direction = null;
            //string orderByAttribute = null;
            //string orderByLastValue = null;
            //Guid? cursor = null;
            //var response = instance.ListAccounts(xSymOrganizationId, accountKey, email, phone, limit, direction, orderByAttribute, orderByLastValue, cursor);
            //Assert.IsType<AccountSearchResultGuidPagedModel>(response);
        }

        /// <summary>
        /// Test UpdateAccount
        /// </summary>
        [Fact]
        public void UpdateAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid xSymOrganizationId = null;
            //AccountForm accountForm = null;
            //var response = instance.UpdateAccount(id, xSymOrganizationId, accountForm);
            //Assert.IsType<AccountResponseResultModel>(response);
        }

        /// <summary>
        /// Test UpdateAccountSync
        /// </summary>
        [Fact]
        public void UpdateAccountSyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid xSymOrganizationId = null;
            //AccountForm accountForm = null;
            //var response = instance.UpdateAccountSync(id, xSymOrganizationId, accountForm);
            //Assert.IsType<AccountResponseResultModel>(response);
        }
    }
}
