/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Symend.Client.Customer.Client;
using Symend.Client.Customer.Api;
// uncomment below to import models
//using Symend.Client.Customer.Model;

namespace Symend.Client.Customer.Test.Api
{
    /// <summary>
    ///  Class for testing ListEventTypesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ListEventTypesApiTests : IDisposable
    {
        private ListEventTypesApi instance;

        public ListEventTypesApiTests()
        {
            instance = new ListEventTypesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListEventTypesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ListEventTypesApi
            //Assert.IsType<ListEventTypesApi>(instance);
        }

        /// <summary>
        /// Test ListCustomerTrailEventTypes
        /// </summary>
        [Fact]
        public void ListCustomerTrailEventTypesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListCustomerTrailEventTypes();
            //Assert.IsType<CustomerTrailEventTypeCollectionModel>(response);
        }
    }
}
