/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Symend.Client.Customer.Client;
using Symend.Client.Customer.Api;
// uncomment below to import models
//using Symend.Client.Customer.Model;

namespace Symend.Client.Customer.Test.Api
{
    /// <summary>
    ///  Class for testing SymPermUpdateAccountApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SymPermUpdateAccountApiTests : IDisposable
    {
        private SymPermUpdateAccountApi instance;

        public SymPermUpdateAccountApiTests()
        {
            instance = new SymPermUpdateAccountApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SymPermUpdateAccountApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SymPermUpdateAccountApi
            //Assert.IsType<SymPermUpdateAccountApi>(instance);
        }

        /// <summary>
        /// Test UpdateAccount
        /// </summary>
        [Fact]
        public void UpdateAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //Guid xSymOrganizationId = null;
            //AccountForm accountForm = null;
            //var response = instance.UpdateAccount(id, xSymOrganizationId, accountForm);
            //Assert.IsType<AccountResponseResultModel>(response);
        }
    }
}
