/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Symend.Client.Customer.Client.OpenAPIDateConverter;

namespace Symend.Client.Customer.Model
{
    /// <summary>
    /// Defines AccountSearchOption
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AccountSearchOption
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum AccountId for value: AccountId
        /// </summary>
        [EnumMember(Value = "AccountId")]
        AccountId = 2,

        /// <summary>
        /// Enum AccountKey for value: AccountKey
        /// </summary>
        [EnumMember(Value = "AccountKey")]
        AccountKey = 3,

        /// <summary>
        /// Enum Email for value: Email
        /// </summary>
        [EnumMember(Value = "Email")]
        Email = 4,

        /// <summary>
        /// Enum Phone for value: Phone
        /// </summary>
        [EnumMember(Value = "Phone")]
        Phone = 5

    }

}
