/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Symend.Client.Customer.Client.OpenAPIDateConverter;

namespace Symend.Client.Customer.Model
{
    /// <summary>
    /// Defines CustomerTrailEventTypeCategory
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CustomerTrailEventTypeCategory
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum AccountUpdates for value: accountUpdates
        /// </summary>
        [EnumMember(Value = "accountUpdates")]
        AccountUpdates = 2,

        /// <summary>
        /// Enum EmailActivities for value: emailActivities
        /// </summary>
        [EnumMember(Value = "emailActivities")]
        EmailActivities = 3,

        /// <summary>
        /// Enum SmsActivities for value: smsActivities
        /// </summary>
        [EnumMember(Value = "smsActivities")]
        SmsActivities = 4,

        /// <summary>
        /// Enum PlaybookActivities for value: playbookActivities
        /// </summary>
        [EnumMember(Value = "playbookActivities")]
        PlaybookActivities = 5,

        /// <summary>
        /// Enum CampaignActivities for value: campaignActivities
        /// </summary>
        [EnumMember(Value = "campaignActivities")]
        CampaignActivities = 6,

        /// <summary>
        /// Enum LandingPageActivities for value: landingPageActivities
        /// </summary>
        [EnumMember(Value = "landingPageActivities")]
        LandingPageActivities = 7

    }

}
