/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Symend.Client.Customer.Client.OpenAPIDateConverter;

namespace Symend.Client.Customer.Model
{
    /// <summary>
    /// Defines DataTargetDefinitionCategory
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataTargetDefinitionCategory
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum KeyDate for value: keyDate
        /// </summary>
        [EnumMember(Value = "keyDate")]
        KeyDate = 2,

        /// <summary>
        /// Enum Customer for value: customer
        /// </summary>
        [EnumMember(Value = "customer")]
        Customer = 3,

        /// <summary>
        /// Enum Contact for value: contact
        /// </summary>
        [EnumMember(Value = "contact")]
        Contact = 4,

        /// <summary>
        /// Enum Billing for value: billing
        /// </summary>
        [EnumMember(Value = "billing")]
        Billing = 5,

        /// <summary>
        /// Enum Account for value: account
        /// </summary>
        [EnumMember(Value = "account")]
        Account = 6,

        /// <summary>
        /// Enum Uncategorized for value: uncategorized
        /// </summary>
        [EnumMember(Value = "uncategorized")]
        Uncategorized = 7,

        /// <summary>
        /// Enum Property for value: property
        /// </summary>
        [EnumMember(Value = "property")]
        Property = 8

    }

}
