/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Symend.Client.Customer.Client.OpenAPIDateConverter;

namespace Symend.Client.Customer.Model
{
    /// <summary>
    /// Defines DataTargetDefinitionStructureType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataTargetDefinitionStructureType
    {
        /// <summary>
        /// Enum Singular for value: singular
        /// </summary>
        [EnumMember(Value = "singular")]
        Singular = 1,

        /// <summary>
        /// Enum Collection for value: collection
        /// </summary>
        [EnumMember(Value = "collection")]
        Collection = 2
    }

}
