/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Symend.Client.Customer.Client.OpenAPIDateConverter;

namespace Symend.Client.Customer.Model
{
    /// <summary>
    /// GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter
    /// </summary>
    [DataContract(Name = "GetDataTargetDefinitions_DataTargetDefinitionSearchCriteria_parameter")]
    public partial class GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter : IEquatable<GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name = "dataType", EmitDefaultValue = false)]
        public DataTargetDefinitionDataType? DataType { get; set; }

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public DataTargetDefinitionCategory? Category { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter" /> class.
        /// </summary>
        /// <param name="dataType">dataType.</param>
        /// <param name="category">category.</param>
        /// <param name="allowMapping">allowMapping.</param>
        /// <param name="isUniqueId">isUniqueId.</param>
        public GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter(DataTargetDefinitionDataType? dataType = default(DataTargetDefinitionDataType?), DataTargetDefinitionCategory? category = default(DataTargetDefinitionCategory?), bool? allowMapping = default(bool?), bool? isUniqueId = default(bool?))
        {
            this.DataType = dataType;
            this.Category = category;
            this.AllowMapping = allowMapping;
            this.IsUniqueId = isUniqueId;
        }

        /// <summary>
        /// Gets or Sets AllowMapping
        /// </summary>
        [DataMember(Name = "allowMapping", EmitDefaultValue = true)]
        public bool? AllowMapping { get; set; }

        /// <summary>
        /// Gets or Sets IsUniqueId
        /// </summary>
        [DataMember(Name = "isUniqueId", EmitDefaultValue = true)]
        public bool? IsUniqueId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter {\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  AllowMapping: ").Append(AllowMapping).Append("\n");
            sb.Append("  IsUniqueId: ").Append(IsUniqueId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter);
        }

        /// <summary>
        /// Returns true if GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter instances are equal
        /// </summary>
        /// <param name="input">Instance of GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DataType == input.DataType ||
                    this.DataType.Equals(input.DataType)
                ) && 
                (
                    this.Category == input.Category ||
                    this.Category.Equals(input.Category)
                ) && 
                (
                    this.AllowMapping == input.AllowMapping ||
                    (this.AllowMapping != null &&
                    this.AllowMapping.Equals(input.AllowMapping))
                ) && 
                (
                    this.IsUniqueId == input.IsUniqueId ||
                    (this.IsUniqueId != null &&
                    this.IsUniqueId.Equals(input.IsUniqueId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.DataType.GetHashCode();
                hashCode = (hashCode * 59) + this.Category.GetHashCode();
                if (this.AllowMapping != null)
                {
                    hashCode = (hashCode * 59) + this.AllowMapping.GetHashCode();
                }
                if (this.IsUniqueId != null)
                {
                    hashCode = (hashCode * 59) + this.IsUniqueId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
