/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Symend.Client.Customer.Client.OpenAPIDateConverter;

namespace Symend.Client.Customer.Model
{
    /// <summary>
    /// Defines PublishState
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PublishState
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown = 1,

        /// <summary>
        /// Enum Draft for value: draft
        /// </summary>
        [EnumMember(Value = "draft")]
        Draft = 2,

        /// <summary>
        /// Enum PendingChanges for value: pendingChanges
        /// </summary>
        [EnumMember(Value = "pendingChanges")]
        PendingChanges = 3,

        /// <summary>
        /// Enum Published for value: published
        /// </summary>
        [EnumMember(Value = "published")]
        Published = 4,

        /// <summary>
        /// Enum Archived for value: archived
        /// </summary>
        [EnumMember(Value = "archived")]
        Archived = 5

    }

}
