/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing AccountAttributeResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountAttributeResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountAttributeResponseModel
        //private AccountAttributeResponseModel instance;

        public AccountAttributeResponseModelTests()
        {
            // TODO uncomment below to create an instance of AccountAttributeResponseModel
            //instance = new AccountAttributeResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountAttributeResponseModel
        /// </summary>
        [Fact]
        public void AccountAttributeResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountAttributeResponseModel
            //Assert.IsType<AccountAttributeResponseModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

    }

}
