/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerTrailEventModelV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerTrailEventModelV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerTrailEventModelV2
        //private CustomerTrailEventModelV2 instance;

        public CustomerTrailEventModelV2Tests()
        {
            // TODO uncomment below to create an instance of CustomerTrailEventModelV2
            //instance = new CustomerTrailEventModelV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerTrailEventModelV2
        /// </summary>
        [Fact]
        public void CustomerTrailEventModelV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerTrailEventModelV2
            //Assert.IsType<CustomerTrailEventModelV2>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'PlaybookId'
        /// </summary>
        [Fact]
        public void PlaybookIdTest()
        {
            // TODO unit test for the property 'PlaybookId'
        }
        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }
        /// <summary>
        /// Test the property 'CampaignPersistentId'
        /// </summary>
        [Fact]
        public void CampaignPersistentIdTest()
        {
            // TODO unit test for the property 'CampaignPersistentId'
        }

    }

}
