/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerTrailEventTypeModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerTrailEventTypeModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerTrailEventTypeModel
        //private CustomerTrailEventTypeModel instance;

        public CustomerTrailEventTypeModelTests()
        {
            // TODO uncomment below to create an instance of CustomerTrailEventTypeModel
            //instance = new CustomerTrailEventTypeModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerTrailEventTypeModel
        /// </summary>
        [Fact]
        public void CustomerTrailEventTypeModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerTrailEventTypeModel
            //Assert.IsType<CustomerTrailEventTypeModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'AttributeTypes'
        /// </summary>
        [Fact]
        public void AttributeTypesTest()
        {
            // TODO unit test for the property 'AttributeTypes'
        }
        /// <summary>
        /// Test the property 'SchemaName'
        /// </summary>
        [Fact]
        public void SchemaNameTest()
        {
            // TODO unit test for the property 'SchemaName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
