/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerTrailAttributeTypeModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerTrailAttributeTypeModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerTrailAttributeTypeModel
        //private CustomerTrailAttributeTypeModel instance;

        public CustomerTrailAttributeTypeModelTests()
        {
            // TODO uncomment below to create an instance of CustomerTrailAttributeTypeModel
            //instance = new CustomerTrailAttributeTypeModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerTrailAttributeTypeModel
        /// </summary>
        [Fact]
        public void CustomerTrailAttributeTypeModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerTrailAttributeTypeModel
            //Assert.IsType<CustomerTrailAttributeTypeModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TableName'
        /// </summary>
        [Fact]
        public void TableNameTest()
        {
            // TODO unit test for the property 'TableName'
        }
        /// <summary>
        /// Test the property 'ColumnName'
        /// </summary>
        [Fact]
        public void ColumnNameTest()
        {
            // TODO unit test for the property 'ColumnName'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsDeprecated'
        /// </summary>
        [Fact]
        public void IsDeprecatedTest()
        {
            // TODO unit test for the property 'IsDeprecated'
        }

    }

}
