/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerAttribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerAttributeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerAttribute
        //private CustomerAttribute instance;

        public CustomerAttributeTests()
        {
            // TODO uncomment below to create an instance of CustomerAttribute
            //instance = new CustomerAttribute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerAttribute
        /// </summary>
        [Fact]
        public void CustomerAttributeInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerAttribute
            //Assert.IsType<CustomerAttribute>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AttributeType'
        /// </summary>
        [Fact]
        public void AttributeTypeTest()
        {
            // TODO unit test for the property 'AttributeType'
        }

    }

}
