/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerTrailOptionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerTrailOptionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerTrailOptionModel
        //private CustomerTrailOptionModel instance;

        public CustomerTrailOptionModelTests()
        {
            // TODO uncomment below to create an instance of CustomerTrailOptionModel
            //instance = new CustomerTrailOptionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerTrailOptionModel
        /// </summary>
        [Fact]
        public void CustomerTrailOptionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerTrailOptionModel
            //Assert.IsType<CustomerTrailOptionModel>(instance);
        }


        /// <summary>
        /// Test the property 'AccountSearchOptions'
        /// </summary>
        [Fact]
        public void AccountSearchOptionsTest()
        {
            // TODO unit test for the property 'AccountSearchOptions'
        }
        /// <summary>
        /// Test the property 'EventCategoryOptions'
        /// </summary>
        [Fact]
        public void EventCategoryOptionsTest()
        {
            // TODO unit test for the property 'EventCategoryOptions'
        }

    }

}
