/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing DataTargetDefinitionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataTargetDefinitionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataTargetDefinitionModel
        //private DataTargetDefinitionModel instance;

        public DataTargetDefinitionModelTests()
        {
            // TODO uncomment below to create an instance of DataTargetDefinitionModel
            //instance = new DataTargetDefinitionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataTargetDefinitionModel
        /// </summary>
        [Fact]
        public void DataTargetDefinitionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataTargetDefinitionModel
            //Assert.IsType<DataTargetDefinitionModel>(instance);
        }


        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Fact]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'IsPii'
        /// </summary>
        [Fact]
        public void IsPiiTest()
        {
            // TODO unit test for the property 'IsPii'
        }
        /// <summary>
        /// Test the property 'IsRequired'
        /// </summary>
        [Fact]
        public void IsRequiredTest()
        {
            // TODO unit test for the property 'IsRequired'
        }
        /// <summary>
        /// Test the property 'IsCustom'
        /// </summary>
        [Fact]
        public void IsCustomTest()
        {
            // TODO unit test for the property 'IsCustom'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'AllowMapping'
        /// </summary>
        [Fact]
        public void AllowMappingTest()
        {
            // TODO unit test for the property 'AllowMapping'
        }
        /// <summary>
        /// Test the property 'IsUniqueId'
        /// </summary>
        [Fact]
        public void IsUniqueIdTest()
        {
            // TODO unit test for the property 'IsUniqueId'
        }
        /// <summary>
        /// Test the property 'StructureType'
        /// </summary>
        [Fact]
        public void StructureTypeTest()
        {
            // TODO unit test for the property 'StructureType'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
