/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing DataTargetDefinitionStructureType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataTargetDefinitionStructureTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataTargetDefinitionStructureType
        //private DataTargetDefinitionStructureType instance;

        public DataTargetDefinitionStructureTypeTests()
        {
            // TODO uncomment below to create an instance of DataTargetDefinitionStructureType
            //instance = new DataTargetDefinitionStructureType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataTargetDefinitionStructureType
        /// </summary>
        [Fact]
        public void DataTargetDefinitionStructureTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataTargetDefinitionStructureType
            //Assert.IsType<DataTargetDefinitionStructureType>(instance);
        }



    }

}
