/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing DateTimePagedMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DateTimePagedMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DateTimePagedMetadata
        //private DateTimePagedMetadata instance;

        public DateTimePagedMetadataTests()
        {
            // TODO uncomment below to create an instance of DateTimePagedMetadata
            //instance = new DateTimePagedMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DateTimePagedMetadata
        /// </summary>
        [Fact]
        public void DateTimePagedMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DateTimePagedMetadata
            //Assert.IsType<DateTimePagedMetadata>(instance);
        }


        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Cursor'
        /// </summary>
        [Fact]
        public void CursorTest()
        {
            // TODO unit test for the property 'Cursor'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [Fact]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }

    }

}
