/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter
        //private GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter instance;

        public GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameterTests()
        {
            // TODO uncomment below to create an instance of GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter
            //instance = new GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter
        /// </summary>
        [Fact]
        public void GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameterInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter
            //Assert.IsType<GetCustomerEventsByAccountKeyOrderByDateTimeSearchParameterParameter>(instance);
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'PlaybookId'
        /// </summary>
        [Fact]
        public void PlaybookIdTest()
        {
            // TODO unit test for the property 'PlaybookId'
        }
        /// <summary>
        /// Test the property 'PlaybookName'
        /// </summary>
        [Fact]
        public void PlaybookNameTest()
        {
            // TODO unit test for the property 'PlaybookName'
        }
        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }
        /// <summary>
        /// Test the property 'CampaignName'
        /// </summary>
        [Fact]
        public void CampaignNameTest()
        {
            // TODO unit test for the property 'CampaignName'
        }
        /// <summary>
        /// Test the property 'CampaignPersistentId'
        /// </summary>
        [Fact]
        public void CampaignPersistentIdTest()
        {
            // TODO unit test for the property 'CampaignPersistentId'
        }

    }

}
