/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter
        //private GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter instance;

        public GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameterTests()
        {
            // TODO uncomment below to create an instance of GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter
            //instance = new GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter
        /// </summary>
        [Fact]
        public void GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameterInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter
            //Assert.IsType<GetDataTargetDefinitionsDataTargetDefinitionSearchCriteriaParameter>(instance);
        }


        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'AllowMapping'
        /// </summary>
        [Fact]
        public void AllowMappingTest()
        {
            // TODO unit test for the property 'AllowMapping'
        }
        /// <summary>
        /// Test the property 'IsUniqueId'
        /// </summary>
        [Fact]
        public void IsUniqueIdTest()
        {
            // TODO unit test for the property 'IsUniqueId'
        }

    }

}
