/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing OrderBy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderByTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderBy
        //private OrderBy instance;

        public OrderByTests()
        {
            // TODO uncomment below to create an instance of OrderBy
            //instance = new OrderBy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderBy
        /// </summary>
        [Fact]
        public void OrderByInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderBy
            //Assert.IsType<OrderBy>(instance);
        }


        /// <summary>
        /// Test the property 'Attribute'
        /// </summary>
        [Fact]
        public void AttributeTest()
        {
            // TODO unit test for the property 'Attribute'
        }
        /// <summary>
        /// Test the property 'LastValue'
        /// </summary>
        [Fact]
        public void LastValueTest()
        {
            // TODO unit test for the property 'LastValue'
        }

    }

}
