/*
 * Customer Service API
 *
 * API for Customer Domain Operations
 *
 * The version of the OpenAPI document: v1
 * Contact: support@symend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Symend.Client.Customer.Api;
using Symend.Client.Customer.Model;
using Symend.Client.Customer.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Symend.Client.Customer.Test.Model
{
    /// <summary>
    ///  Class for testing SegmentModelResultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SegmentModelResultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SegmentModelResultModel
        //private SegmentModelResultModel instance;

        public SegmentModelResultModelTests()
        {
            // TODO uncomment below to create an instance of SegmentModelResultModel
            //instance = new SegmentModelResultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SegmentModelResultModel
        /// </summary>
        [Fact]
        public void SegmentModelResultModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SegmentModelResultModel
            //Assert.IsType<SegmentModelResultModel>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
